
CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50) UNIQUE,
    password VARCHAR2(200),
    role VARCHAR2(20)
);

CREATE TABLE employee (
    employeeid NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    department VARCHAR2(50),
    salary NUMBER
);

INSERT INTO users VALUES (1, 'emp1', 'password123', 'employee');
INSERT INTO users VALUES (2, 'hr1', 'password123', 'hr');
INSERT INTO users VALUES (3, 'fin1', 'password123', 'finance');

INSERT INTO employee VALUES (1, 'Employee One', 'Sales', 45000);
INSERT INTO employee VALUES (2, 'HR Head', 'Human Resources', 60000);
INSERT INTO employee VALUES (3, 'Finance Manager', 'Finance', 70000);

COMMIT;


CREATE TABLE payslip (
    payslip_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeid NUMBER,
    base_salary NUMBER,
    bonus NUMBER,
    leaves NUMBER,
    leave_deduction NUMBER,
    net_salary NUMBER,
    pay_month VARCHAR2(20),
    created_at DATE DEFAULT SYSDATE,
    FOREIGN KEY(employeeid) REFERENCES employee(employeeid)
);


CREATE OR REPLACE PACKAGE payroll_pkg AS
    PROCEDURE generate_payslip(p_emp_id NUMBER, p_bonus NUMBER, p_leaves NUMBER);
END payroll_pkg;
/

CREATE OR REPLACE PACKAGE BODY payroll_pkg AS
    PROCEDURE generate_payslip(p_emp_id NUMBER, p_bonus NUMBER, p_leaves NUMBER) IS
        v_base_salary NUMBER;
        v_leave_deduction NUMBER;
        v_net_salary NUMBER;
    BEGIN
        SELECT salary INTO v_base_salary
        FROM employee
        WHERE employeeid = p_emp_id;

        v_leave_deduction := p_leaves * 500;
        v_net_salary := v_base_salary + p_bonus - v_leave_deduction;

        INSERT INTO payslip (
            employeeid, base_salary, bonus, leaves, leave_deduction, net_salary, pay_month
        ) VALUES (
            p_emp_id, v_base_salary, p_bonus, p_leaves, v_leave_deduction, v_net_salary, TO_CHAR(SYSDATE, 'MON-YYYY')
        );

        UPDATE employee
        SET salary = v_net_salary
        WHERE employeeid = p_emp_id;

        COMMIT;
    END;
END payroll_pkg;
/
