-- Create Employee Table
CREATE TABLE Employee (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Department VARCHAR2(50),
    Salary NUMBER
);

-- Create Attendance Table
CREATE TABLE Attendances (
    AttendanceID NUMBER PRIMARY KEY,
    EmployeeID NUMBER,
    AttendanceDays NUMBER,
    LeaveDays NUMBER,
    Bonus NUMBER,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
);

drop table users;
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) UNIQUE,
    Password VARCHAR2(100),
    Role VARCHAR2(20),
    EmployeeID NUMBER,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
);
-- Insert initial data into Employee Table
INSERT INTO Employee (EmployeeID, Name, Department, Salary) VALUES (4, 'John Doe', 'HR', 50000);
INSERT INTO Employee (EmployeeID, Name, Department, Salary) VALUES (5, 'Jane Smith', 'Accounting', 60000);
INSERT INTO Employee (EmployeeID, Name, Department, Salary) VALUES (6, 'Jane Smith', 'Employee', 60000);

-- Insert initial data into Attendance Table
INSERT INTO Attendances (AttendanceID, EmployeeID, AttendanceDays, LeaveDays, Bonus) VALUES (1, 4, 20, 2, 500);
INSERT INTO Attendances (AttendanceID, EmployeeID, AttendanceDays, LeaveDays, Bonus) VALUES (2, 5, 22, 1, 300);
INSERT INTO Attendances (AttendanceID, EmployeeID, AttendanceDays, LeaveDays, Bonus) VALUES (3, 6, 22, 1, 300);

INSERT INTO Users (Username, Password, Role, EmployeeID) VALUES ('admin', 'adminpass', 'hr', 4);
INSERT INTO Users (Username, Password, Role, EmployeeID) VALUES ('accountant1', 'accountantpass', 'accountant', 5);
INSERT INTO Users (Username, Password, Role, EmployeeID) VALUES ('employee1', 'employeepass', 'employee', 6);  
    
    
    